name: Ejecutar Script Python

on:
  push:
    branches:
      - main

jobs:
  ejecutar_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install ffmpeg -y

    - name: Ejecutar script Python
      run: |
        python ScrapURLChannel.py
